// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTPruZyBfBY7Yp8Q6yK5xphiVjq44uuw',
    appId: '1:398126477652:web:a5104cf537daa5894f98c1',
    messagingSenderId: '398126477652',
    projectId: 'gym-app-dcd38',
    authDomain: 'gym-app-dcd38.firebaseapp.com',
    storageBucket: 'gym-app-dcd38.firebasestorage.app',
    measurementId: 'G-3FXR3X435K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHANJ1JkvzuSIkp-CFpvdg2PYTvsPzbKw',
    appId: '1:398126477652:android:20f0a43e7b2d20214f98c1',
    messagingSenderId: '398126477652',
    projectId: 'gym-app-dcd38',
    storageBucket: 'gym-app-dcd38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA997cXqStknr0csgkjsAgAwObLOpYRTq4',
    appId: '1:398126477652:ios:0902e2d7e713aa834f98c1',
    messagingSenderId: '398126477652',
    projectId: 'gym-app-dcd38',
    storageBucket: 'gym-app-dcd38.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA997cXqStknr0csgkjsAgAwObLOpYRTq4',
    appId: '1:398126477652:ios:0902e2d7e713aa834f98c1',
    messagingSenderId: '398126477652',
    projectId: 'gym-app-dcd38',
    storageBucket: 'gym-app-dcd38.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgTPruZyBfBY7Yp8Q6yK5xphiVjq44uuw',
    appId: '1:398126477652:web:76b02fe0662d60d34f98c1',
    messagingSenderId: '398126477652',
    projectId: 'gym-app-dcd38',
    authDomain: 'gym-app-dcd38.firebaseapp.com',
    storageBucket: 'gym-app-dcd38.firebasestorage.app',
    measurementId: 'G-R8HFCE3BQB',
  );
}
